### ISSUE TITLE
Add new device screen

### ISSUE THREAD

**Issue by CodeMaester01** [cse442-spring-2020-offering/cse442-semester-project-indra-infared-remote-access#12]
Task Test:
1. From My Devices home screen, select plus icon
2. Screen prompting to add new device is displayed
3. Click search icon next to Add New Remote Configuration
4. Type "lg"
5. Select "lg/42H3000"
6. Device is successfully found and config file is displayed for device

**Comment by tjchase34** [comment]
- Search box needs to have dummy data that comes up when you click it (E.g. VizioTV - add device)
- Doesn't actually have to add it to the devices screen
- Emulate the search with mock data and adding options, etc
