### ISSUE TITLE
Create server database table to store user account information

### ISSUE THREAD

**Issue by sam21marchant** [cse442-spring-2020-offering/cse442-semester-project-indra-infared-remote-access#16]
Task Test:

1. Connect to the INDRA MongoDB Atlas database by any means (this task test will assume use of MongoDB compass, a desktop tool). Connection link is: mongodb+srv://admin:<password>@cluster0-avgnl.mongodb.net/test
2. Verify the "indra-users" database exists
3. Verify the "users" collection exists within the "indra-users" database

**Comment by tjchase34** [comment]
Make a better task test (write down what you're actually doing to see that database is gucci)

**Comment by tjchase34** [comment]
Evidence of task test completion:

![image.png](https://images.zenhubusercontent.com/5e3b441ec167455e9b61d9f6/6648d13b-3e52-490c-93f0-b4391c6dbc94)
