### ISSUE TITLE
Send IR remote command from app to the server

### ISSUE THREAD

**Issue by sam21marchant** [cse442-spring-2020-offering/cse442-semester-project-indra-infared-remote-access#24]
Task Test:
From the TV remote screen, pressing any button should pop up a message on the console under the "Connection Alerts" tag. If the app successfully connects to the server, should print "Successfully connected to server". If fails, print "Failed to connect to server".

**Comment by CodeMaester01** [comment]
Doing research on sending IR commands to a python server from android studio. Currently agreed with group on using socket.io for server.
