### ISSUE TITLE
Research python socketio

### ISSUE THREAD

**Issue by sam21marchant** [cse442-spring-2020-offering/cse442-semester-project-indra-infared-remote-access#46]
Documentation that highlights the important features of the socketio server library.

Task test:
    Setup a dummy socket server to listen for requests
    Show that the server can handle these requests

**Comment by nuhash9** [comment]
Research:
https://docs.google.com/document/d/1CpOuToYR5sOK5IYX4GpBIy2Xv0hUN6eZLVj1zau4TIo/edit?usp=sharing
