### ISSUE TITLE
Research Socketio Python client

### ISSUE THREAD

**Issue by sam21marchant** [cse442-spring-2020-offering/cse442-semester-project-indra-infared-remote-access#47]
Document important features of socketio Python client

Task test:
Dummy client that can connect to a server and send a message.
Server should receive that message and print it out

**Comment by tjchase34** [comment]
Note: https://docs.google.com/document/d/19KPcDixepc6a_K9isLnRgThNto3uJ5TzwAIrllhyUh0/edit?usp=sharing
