### ISSUE TITLE
Research LIRC remotes database and how to search it

### ISSUE THREAD

**Issue by sam21marchant** [cse442-spring-2020-offering/cse442-semester-project-indra-infared-remote-access#48]
Provide a digest of the LIRC Database API

Bonus:
-Demonstrate searching that database with some python code
-Print to the console the config file that was searched for

**Comment by CodeMaester01** [comment]
https://docs.google.com/document/d/10CMqTjNMoOdUDlx9v1yj86rK_qcsO2ixQszODzKTEx4/edit
